name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish TechnicalInterview.GenericLibrary/TechnicalInterview.GenericLibrary.csproj -c Release -o artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: TechnicalInterview.GenericLibrary/artifact/**
        

